# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Prevent Python from writing pyc files and buffering stdout/stderr
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy project files
COPY . .

# Remove the Python version requirement to allow building on 3.12
RUN sed -i '/requires-python/d' pyproject.toml

# Install the package and its dependencies
RUN pip install --no-cache-dir .

# Default command to run the MCP server
CMD ["ynab-mcp"]
